server:
  port: 8081

spring:
  profiles:
    active: docker
  application:
    oauthUserName: user
    oauthPassword: password
    oauthClientId: acme
    oauthSecret: acmesecret
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
logging:
  level:
    demo: info
---
spring:
  profiles: docker
  application:
    name: sbtest
    description: Spring Cloud Demo docekr env
    version: ${spring.application.description} @project.version@
    remoteGetIndexUrl: http://127.0.0.1:8080/v1/index/
    remoteGetStock: http://127.0.0.1:8080/v1/getStock
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://127.0.0.1:8000/eureka/

